# Generated by Django 4.2 on 2024-07-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Ссылка"
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Именная ссылка",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(max_length=200, verbose_name="Название меню"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tree.menuitem",
                        verbose_name="Родительский пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "меню",
                "verbose_name_plural": "меню",
            },
        ),
    ]
